### ISSUE TITLE
노티피케이션이 자꾸 날라가네요 ㅠㅠ

### ISSUE THREAD

**Issue by outsideris** [FRENDS-Research/nodejs.kr#9]
이 프로젝트에서 이슈남기거나 뭔가를 하면 자꾸
fallroot, unlogicaldev, zziuni, j2p님한테 노티피케이션이 날라갑니다. ㅠㅠ
멤버로 봤을때는 카푸치노 스터디때 이 계정을 만들었을대 뭔가 셋팅이 된것 같은데
왜 날라가는지 모르겠어요 
엉엉

**Comment by kyungw00k** [comment]
(같이 참여하라는 압박성 노티는 아닐테지만..) 아마도 같은 그룹 안에 있어서 그럴꺼라고 생각됩니다만..

**Comment by outsideris** [comment]
어드민에 보니 저장소에 카푸치노 그룹이 포함되어 있어서 그랬던 거군요. 삭제하니까 노티안날라가는것 같아요.
